server:
  port: 8090
  
management:
  security:
    enabled: false 
    
  
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ksr4innovation/springcloudconfigrepo1
          #username:
          #password:
          search-paths:
          - emp* 
          
          
          



          
       
           
              
           